server:
  port: 80
spring:
  datasource:
    name: smartdz
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/smartdz?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
  #  redis:
  #    database: 1
  #    host: 127.0.0.1
  #    port: 6379
  #    password:
  #    jedis:
  #      pool:
  #        max-active: 10
  #        max-idle: 10
  #        min-idle: 5
  #        max-wait: -1
  #    timeout: 1000
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: LEGACYHTML5
    cache: false
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 104857600
mybatis:
  type-aliases-package: com.smartdz.dzboss.domain
  mapper-locations: classpath:mapper/*.xml
pagehelper:
  # helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql